from setuptools import setup, find_packages

setup(
    name='ecoperceiver',
    version='0.2.1',
    author='Matthew Fortier',
    author_email='fortier.matt@gmail.com',
    description='A multimodal model and dataloader for carbon flux modelling',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/mjfortier/EcoPerceiver',
    packages=find_packages(),
    install_requires=[
        'numpy==1.26.4',
        'pandas==2.2.3',
        # 'torch==2.7.0',
        'torch==2.6.0',
        # 'torchvision==0.22.0',
        'torchvision==0.21.0',
        'einops==0.8.0',
        'tqdm==4.67.0',
        'rioxarray==0.19.0',
        # 'rasterio==1.4.3',
        # 'xarray==2025.7.0',
        'xarray==2025.7.1',
        'netCDF4==1.7.2',
        'dask==2025.5.1',
    ],
    python_requires='>=3.12',
)
